#!/bin/sh
SUFFIX=$1
CLIENT_NAME="alice"
FDIR=`dirname $0`
FDIR_ESC=$(echo $FDIR | sed 's/\//\\\//g')
RELEASE=`ls -1 $FDIR/../ebin/$CLIENT_NAME*.$SUFFIX | sed 's/ /\n/g' | sed "s:\($FDIR_ESC/../ebin/beehive-\)\(.*\)\(\.$SUFFIX\):\2 \1\2\3:g" | awk -F '.' '{ ver=1000000*\$1 + 1000*\$2 + \$3; printf "%010d %s\n", ver, \$0}' | sort | awk '{print \$3}' | tail -n 1`
echo $RELEASE
